import logging
from typing import List, Dict, Any
from app.rag.vector_store import VectorStoreWrapper
from app.agents.state import AgentState

logger = logging.getLogger("app.agents.retrieval")

async def retrieval_node(state: AgentState) -> dict:
    """
    Retrieval Agent.
    Executes hybrid search (BM25 + Semantic + Rerank) against ChromaDB.
    Operates at zero LLM cost (runs completely local queries).
    """
    logger.info("Starting Retrieval Agent execution")
    question = state["question"]
    owner_id = state.get("user_id", 999)
    
    # Extract search variations from the plan list if generated by the Research Agent
    search_queries = [question]
    plan = state.get("plan", [])
    for task in plan:
        if task.startswith("Search variation: ") or task not in plan[:3]:
            # Clean up the prefix if present
            clean_q = task.replace("Search variation: ", "").strip()
            if clean_q and clean_q not in search_queries:
                search_queries.append(clean_q)
                
    logger.info(f"Retrieval queries to process: {search_queries}")
    
    workspace_id = state.get("workspace_id")
    document_id = state.get("document_id")
    allowed_doc_ids = None
    
    if document_id:
        allowed_doc_ids = {document_id}
        logger.info(f"Single Document query filter active. Allowed Document ID: {document_id}")
    elif workspace_id:
        try:
            from app.database.session import SessionLocal
            from app.models.workspace import Workspace
            db = SessionLocal()
            workspace = db.query(Workspace).filter(Workspace.id == workspace_id).first()
            if workspace:
                allowed_doc_ids = set([doc.id for doc in workspace.documents])
                logger.info(f"Workspace {workspace_id} filtering. Allowed Document IDs: {allowed_doc_ids}")
            db.close()
        except Exception as we:
            logger.error(f"Failed to fetch workspace documents: {we}", exc_info=True)

    # Execute search queries and deduplicate
    vs = VectorStoreWrapper()
    retrieved_items: List[Dict[str, Any]] = []
    seen_ids = set()
    
    for q in search_queries[:3]:  # Limit to top 3 queries to avoid redundant I/O
        try:
            results = vs.hybrid_search(query=q, limit=4, owner_id=owner_id)
            for res in results:
                if allowed_doc_ids is not None:
                    meta = res.get("metadata")
                    meta_doc_id = meta.get("document_id") if meta else None
                    if meta_doc_id not in allowed_doc_ids:
                        continue
                doc_id = res["id"]
                if doc_id not in seen_ids:
                    seen_ids.add(doc_id)
                    retrieved_items.append(res)
        except Exception as e:
            logger.error(f"Hybrid search failed for query '{q}': {e}", exc_info=True)
            
    # Sort final merged results by fused/rerank scores
    retrieved_items = sorted(
        retrieved_items, 
        key=lambda x: x.get("rerank_score", x.get("fused_score", 0.0)), 
        reverse=True
    )[:6]
    
    # 4. Query Neo4j Graph Database for related entities (Graph RAG)
    try:
        import re
        from app.rag.neo4j_client import Neo4jClient
        
        # Simple noun extraction from query and search variations
        all_terms = " ".join(search_queries)
        words = re.findall(r'\b[A-Za-z]{4,}\b', all_terms)
        stop_words = {"what", "when", "where", "which", "who", "whom", "this", "that", "there", "their", "about", "database", "query", "search", "variation"}
        entities = list(set([w for w in words if w.lower() not in stop_words]))
        
        if entities:
            logger.info(f"Retrieving Neo4j graph relationships for entities: {entities}")
            neo4j = Neo4jClient()
            relations = neo4j.query_relationships(entities)
            if relations:
                graph_text = "Structured Knowledge Graph Facts:\n" + "\n".join([
                    f"- ({r['source']}) -[{r['relation']}]-> ({r['target']})" for r in relations
                ])
                logger.info(f"Graph RAG: merged {len(relations)} facts into context.")
                # Inject graph context as a first-class source chunk
                retrieved_items.insert(0, {
                    "id": "graph_database_relations",
                    "content": graph_text,
                    "metadata": {
                        "filename": "Neo4j Knowledge Graph",
                        "page_number": "KG"
                    }
                })
    except Exception as ge:
        logger.error(f"Graph RAG retrieval failed: {ge}", exc_info=True)
        
    logger.info(f"Retrieval Agent finished. Total context items (vector + graph): {len(retrieved_items)}.")
    return {
        "retrieved_context": retrieved_items
    }
